web:
  image: nginx:latest
  ports: 
    - "8888:80"
  volumes: 
    - ./api:/cs450-backend
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: ./api
  volumes: 
    - ./api:/cs450-backend
  env_file:
    - dev.env
  links:
    - mysql
  
mysql:
  image: mysql:8.0.23
  ports:
    - "3306:3306"
  volumes:
    - ./db/sql:/docker-entrypoint-initdb.d
  env_file:
    - dev.env
  environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes

composer:
  image: composer:latest
  command: ["composer", "install"]
  volumes:
    - ./api:/app
