version: "3.9"
services:
  web:
    image: nginx:latest
    ports:
      - "8888:8888"
    volumes:
      - ./api:/cs450-backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./api
    volumes:
      - ./api:/var/www/html
    env_file:
      - dev.env
    links:
      - mysql

  mysql:
    image: mysql:8.0.23
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    env_file:
      - dev.env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - ./api:/app

  frontend:
    profiles: ["frontend"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    stdin_open: true
    tty: true
    environment:
      - DOCKER_UI=true
      - CHOKIDAR_USEPOLLING=true
    links:
      - web
