web:
  image: nginx:latest
  ports: 
    - "8888:80"
  volumes: 
    - ../api:/cs450-backend
    - ./default.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  build: .
  volumes: 
    - ../api:/cs450-backend
  environment:
    - MYSQL_DATABASE=cs450
    - MYSQL_USER=cs450db_user
    - MYSQL_PASSWORD=tomtit.TAD.inward
  links:
    - mysql

mysql:
  image: mysql:8.0.23
  ports:
    - "3306:3306"
  volumes:
    - ../db/sql:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_ROOT_PASSWORD=porch.SPIKY.lamia
    - MYSQL_DATABASE=cs450
    - MYSQL_USER=cs450db_user
    - MYSQL_PASSWORD=tomtit.TAD.inward
